spring.application.name=demo

spring.data.mongodb.uri=mongodb+srv://sukhendu_bera:Sbfin12345@cluster0.gk0djkt.mongodb.net/portfoliodb?retryWrites=true&w=majority&appName=Cluster0

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bsukhendu48@gmail.com
spring.mail.password=fdboozcdrlfgaahr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true